openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
  description: API for scraping images
paths:
  /api/scrape:
    get:
      summary: Scrape images from a given URL
      parameters:
        - name: anime
          in: query
          description: Name of the anime
          required: true
          schema:
            type: string
        - name: chapter
          in: query
          description: Chapter number
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  images:
                    type: array
                    items:
                      type: string
